
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Apr 23 20:07:09 EET 2018
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.*;

/** CUP v0.10k generated parser.
  * @version Mon Apr 23 20:07:09 EET 2018
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\034\000\002\003\004\000\002\002\004\000\002\003" +
    "\002\000\002\004\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\005\006\000\002\006\005\000\002\006\005\000\002" +
    "\007\010\000\002\010\007\000\002\013\005\000\002\013" +
    "\004\000\002\012\004\000\002\012\003\000\002\011\010" +
    "\000\002\011\007\000\002\014\003\000\002\014\003\000" +
    "\002\014\004\000\002\014\004\000\002\015\005\000\002" +
    "\015\006\000\002\015\007\000\002\015\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\071\000\020\002\uffff\003\uffff\007\uffff\010\uffff\015" +
    "\uffff\031\uffff\033\uffff\001\002\000\020\002\013\003\017" +
    "\007\007\010\014\015\005\031\012\033\015\001\002\000" +
    "\004\012\071\001\002\000\020\002\ufffd\003\ufffd\007\ufffd" +
    "\010\ufffd\015\ufffd\031\ufffd\033\ufffd\001\002\000\004\033" +
    "\057\001\002\000\020\002\ufffc\003\ufffc\007\ufffc\010\ufffc" +
    "\015\ufffc\031\ufffc\033\ufffc\001\002\000\020\002\ufffe\003" +
    "\ufffe\007\ufffe\010\ufffe\015\ufffe\031\ufffe\033\ufffe\001\002" +
    "\000\004\033\043\001\002\000\004\002\000\001\002\000" +
    "\006\024\026\033\025\001\002\000\004\056\022\001\002" +
    "\000\020\002\001\003\001\007\001\010\001\015\001\031" +
    "\001\033\001\001\002\000\020\002\ufff9\003\ufff9\007\ufff9" +
    "\010\ufff9\015\ufff9\031\ufff9\033\ufff9\001\002\000\020\002" +
    "\ufffa\003\ufffa\007\ufffa\010\ufffa\015\ufffa\031\ufffa\033\ufffa" +
    "\001\002\000\020\002\ufffb\003\ufffb\007\ufffb\010\ufffb\015" +
    "\ufffb\031\ufffb\033\ufffb\001\002\000\006\026\024\027\023" +
    "\001\002\000\020\002\ufff6\003\ufff6\007\ufff6\010\ufff6\015" +
    "\ufff6\031\ufff6\033\ufff6\001\002\000\020\002\ufff7\003\ufff7" +
    "\007\ufff7\010\ufff7\015\ufff7\031\ufff7\033\ufff7\001\002\000" +
    "\010\057\031\060\032\073\034\001\002\000\004\033\027" +
    "\001\002\000\004\073\030\001\002\000\020\002\uffe8\003" +
    "\uffe8\007\uffe8\010\uffe8\015\uffe8\031\uffe8\033\uffe8\001\002" +
    "\000\010\004\uffec\033\uffec\056\042\001\002\000\010\004" +
    "\uffed\033\uffed\056\041\001\002\000\006\004\036\033\035" +
    "\001\002\000\020\002\uffe9\003\uffe9\007\uffe9\010\uffe9\015" +
    "\uffe9\031\uffe9\033\uffe9\001\002\000\004\073\040\001\002" +
    "\000\004\073\037\001\002\000\020\002\uffe6\003\uffe6\007" +
    "\uffe6\010\uffe6\015\uffe6\031\uffe6\033\uffe6\001\002\000\020" +
    "\002\uffe7\003\uffe7\007\uffe7\010\uffe7\015\uffe7\031\uffe7\033" +
    "\uffe7\001\002\000\006\004\uffeb\033\uffeb\001\002\000\006" +
    "\004\uffea\033\uffea\001\002\000\004\064\044\001\002\000" +
    "\006\033\045\065\046\001\002\000\006\065\ufff0\067\054" +
    "\001\002\000\004\073\052\001\002\000\004\065\050\001" +
    "\002\000\004\073\051\001\002\000\020\002\uffef\003\uffef" +
    "\007\uffef\010\uffef\015\uffef\031\uffef\033\uffef\001\002\000" +
    "\020\002\uffee\003\uffee\007\uffee\010\uffee\015\uffee\031\uffee" +
    "\033\uffee\001\002\000\004\065\ufff1\001\002\000\004\033" +
    "\055\001\002\000\006\065\ufff2\067\054\001\002\000\004" +
    "\065\ufff3\001\002\000\004\035\060\001\002\000\004\030" +
    "\061\001\002\000\004\064\064\001\002\000\004\073\063" +
    "\001\002\000\020\002\ufff4\003\ufff4\007\ufff4\010\ufff4\015" +
    "\ufff4\031\ufff4\033\ufff4\001\002\000\004\004\065\001\002" +
    "\000\004\067\066\001\002\000\004\004\067\001\002\000" +
    "\004\065\070\001\002\000\004\073\ufff5\001\002\000\004" +
    "\011\072\001\002\000\004\013\073\001\002\000\020\002" +
    "\ufff8\003\ufff8\007\ufff8\010\ufff8\015\ufff8\031\ufff8\033\ufff8" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\071\000\004\003\003\001\001\000\016\004\015\005" +
    "\010\006\005\010\007\011\020\015\017\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\032\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\012\046\001\001" +
    "\000\004\013\052\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\013\055\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\007\061" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // while_stmnt ::= WH ID bool_expr INT SC 
            {
              Boolean RESULT = null;
		RESULT = true;
              CUP$parser$result = new java_cup.runtime.Symbol(11/*while_stmnt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // while_stmnt ::= WH ID bool_expr ID SC 
            {
              Boolean RESULT = null;
		RESULT = true;
              CUP$parser$result = new java_cup.runtime.Symbol(11/*while_stmnt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // while_stmnt ::= WH NT ID SC 
            {
              Boolean RESULT = null;
		RESULT = true;
              CUP$parser$result = new java_cup.runtime.Symbol(11/*while_stmnt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // while_stmnt ::= WH ID SC 
            {
              Boolean RESULT = null;
		RESULT = true;
              CUP$parser$result = new java_cup.runtime.Symbol(11/*while_stmnt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // bool_expr ::= LT AO 
            {
              Boolean RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*bool_expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // bool_expr ::= GT AO 
            {
              Boolean RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*bool_expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // bool_expr ::= LT 
            {
              Boolean RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*bool_expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // bool_expr ::= GT 
            {
              Boolean RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*bool_expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // def_stmnt ::= DF ID LB RB SC 
            {
              Boolean RESULT = null;
		RESULT = true;
              CUP$parser$result = new java_cup.runtime.Symbol(7/*def_stmnt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // def_stmnt ::= DF ID LB params RB SC 
            {
              Boolean RESULT = null;
		RESULT = true;
              CUP$parser$result = new java_cup.runtime.Symbol(7/*def_stmnt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // params ::= ID 
            {
              Boolean RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*params*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // params ::= ID params_help 
            {
              Boolean RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*params*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // params_help ::= FA ID 
            {
              Boolean RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*params_help*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // params_help ::= FA ID params_help 
            {
              Boolean RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*params_help*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // for_stmnt ::= FOR ID IN range_fn SC 
            {
              Boolean RESULT = null;
		RESULT = true;
              CUP$parser$result = new java_cup.runtime.Symbol(6/*for_stmnt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // range_fn ::= RG LB INT FA INT RB 
            {
              Boolean RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*range_fn*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // bool_stmnt ::= ID AO FL 
            {
              Boolean RESULT = null;
		RESULT = true;
              CUP$parser$result = new java_cup.runtime.Symbol(4/*bool_stmnt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // bool_stmnt ::= ID AO TR 
            {
              Boolean RESULT = null;
		RESULT = true;
              CUP$parser$result = new java_cup.runtime.Symbol(4/*bool_stmnt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // import_stmnt ::= FR PK IM FC 
            {
              Boolean RESULT = null;
		RESULT = true;
              CUP$parser$result = new java_cup.runtime.Symbol(3/*import_stmnt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // statement ::= error 
            {
              Boolean RESULT = null;
		RESULT = false;
              CUP$parser$result = new java_cup.runtime.Symbol(2/*statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // statement ::= while_stmnt 
            {
              Boolean RESULT = null;
		int wsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int wsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Boolean ws = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		RESULT = ws;
              CUP$parser$result = new java_cup.runtime.Symbol(2/*statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // statement ::= def_stmnt 
            {
              Boolean RESULT = null;
		int dsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int dsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Boolean ds = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		RESULT = ds;
              CUP$parser$result = new java_cup.runtime.Symbol(2/*statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // statement ::= for_stmnt 
            {
              Boolean RESULT = null;
		int flleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int flright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Boolean fl = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		RESULT = fl;
              CUP$parser$result = new java_cup.runtime.Symbol(2/*statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // statement ::= bool_stmnt 
            {
              Boolean RESULT = null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Boolean b = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		RESULT = b;
              CUP$parser$result = new java_cup.runtime.Symbol(2/*statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // statement ::= import_stmnt 
            {
              Boolean RESULT = null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Boolean s = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		RESULT = s;
              CUP$parser$result = new java_cup.runtime.Symbol(2/*statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= 
            {
              Boolean RESULT = null;
		RESULT = true;
              CUP$parser$result = new java_cup.runtime.Symbol(1/*program*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Boolean start_val = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= program statement 
            {
              Boolean RESULT = null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Boolean p = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Boolean e = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		RESULT = p && e;
              CUP$parser$result = new java_cup.runtime.Symbol(1/*program*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

