
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Apr 22 20:58:32 EET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DL = 25;
  public static final int PS = 34;
  public static final int GL = 31;
  public static final int PR = 9;
  public static final int ST = 27;
  public static final int MO = 40;
  public static final int PO = 39;
  public static final int AD = 18;
  public static final int DF = 22;
  public static final int AA = 53;
  public static final int SM = 51;
  public static final int PK = 7;
  public static final int DB = 42;
  public static final int MB = 41;
  public static final int SC = 56;
  public static final int INT = 2;
  public static final int YD = 33;
  public static final int FR = 10;
  public static final int IS = 32;
  public static final int LT = 44;
  public static final int CN = 15;
  public static final int LS = 54;
  public static final int CL = 23;
  public static final int RT = 35;
  public static final int FL = 20;
  public static final int IN = 26;
  public static final int LP = 5;
  public static final int OR = 16;
  public static final int RS = 55;
  public static final int IM = 6;
  public static final int IND = 3;
  public static final int FI = 28;
  public static final int LM = 30;
  public static final int IF = 11;
  public static final int FC = 8;
  public static final int ID = 24;
  public static final int FA = 52;
  public static final int ELF = 36;
  public static final int LC = 47;
  public static final int EOF = 0;
  public static final int RG = 21;
  public static final int LB = 49;
  public static final int RC = 48;
  public static final int error = 1;
  public static final int UD = 57;
  public static final int RB = 50;
  public static final int EX = 14;
  public static final int BR = 37;
  public static final int KW = 4;
  public static final int EQ = 46;
  public static final int TY = 13;
  public static final int NT = 17;
  public static final int EI = 12;
  public static final int NN = 29;
  public static final int TR = 19;
  public static final int GT = 45;
  public static final int AO = 43;
  public static final int DO = 38;
}

