
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 26 15:44:58 EET 2018
//----------------------------------------------------

package Compilers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DL = 26;
  public static final int PS = 35;
  public static final int GL = 32;
  public static final int PR = 10;
  public static final int ST = 28;
  public static final int MO = 41;
  public static final int PO = 40;
  public static final int AD = 19;
  public static final int DF = 23;
  public static final int AA = 54;
  public static final int SM = 52;
  public static final int PK = 8;
  public static final int DB = 43;
  public static final int MB = 42;
  public static final int SC = 57;
  public static final int INT = 2;
  public static final int YD = 34;
  public static final int FOR = 5;
  public static final int FR = 11;
  public static final int IS = 33;
  public static final int LT = 45;
  public static final int CN = 16;
  public static final int LS = 55;
  public static final int CL = 24;
  public static final int RT = 36;
  public static final int FL = 21;
  public static final int IN = 27;
  public static final int OR = 17;
  public static final int RS = 56;
  public static final int IM = 7;
  public static final int IND = 3;
  public static final int FI = 29;
  public static final int LM = 31;
  public static final int FC = 9;
  public static final int ID = 25;
  public static final int FA = 53;
  public static final int ELF = 37;
  public static final int LC = 48;
  public static final int EOF = 0;
  public static final int RG = 22;
  public static final int LB = 50;
  public static final int RC = 49;
  public static final int error = 1;
  public static final int UD = 58;
  public static final int RB = 51;
  public static final int EX = 15;
  public static final int BR = 38;
  public static final int KW = 4;
  public static final int EQ = 47;
  public static final int ERROR = 61;
  public static final int TY = 14;
  public static final int NT = 18;
  public static final int EI = 13;
  public static final int NN = 30;
  public static final int TR = 20;
  public static final int NL = 59;
  public static final int IFS = 12;
  public static final int WH = 6;
  public static final int DED = 60;
  public static final int GT = 46;
  public static final int AO = 44;
  public static final int DO = 39;
}

