
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 26 23:09:12 EET 2018
//----------------------------------------------------

package Compilers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DL = 27;
  public static final int PS = 36;
  public static final int GL = 33;
  public static final int PR = 11;
  public static final int ST = 29;
  public static final int MO = 42;
  public static final int PO = 41;
  public static final int AD = 20;
  public static final int DF = 24;
  public static final int AA = 55;
  public static final int SM = 53;
  public static final int PK = 9;
  public static final int DB = 44;
  public static final int MB = 43;
  public static final int SC = 58;
  public static final int INT = 3;
  public static final int YD = 35;
  public static final int FOR = 6;
  public static final int FR = 12;
  public static final int IS = 34;
  public static final int LT = 46;
  public static final int CN = 17;
  public static final int LS = 56;
  public static final int CL = 25;
  public static final int RT = 37;
  public static final int FL = 22;
  public static final int IN = 28;
  public static final int OR = 18;
  public static final int RS = 57;
  public static final int IM = 8;
  public static final int IND = 4;
  public static final int FI = 30;
  public static final int LM = 32;
  public static final int FC = 10;
  public static final int ID = 26;
  public static final int FA = 54;
  public static final int ELF = 38;
  public static final int LC = 49;
  public static final int EOF = 0;
  public static final int RG = 23;
  public static final int LB = 51;
  public static final int RC = 50;
  public static final int error = 1;
  public static final int UD = 59;
  public static final int RB = 52;
  public static final int EX = 16;
  public static final int BR = 39;
  public static final int KW = 5;
  public static final int EQ = 48;
  public static final int ERROR = 61;
  public static final int TY = 15;
  public static final int NT = 19;
  public static final int EI = 14;
  public static final int NN = 31;
  public static final int TR = 21;
  public static final int NL = 2;
  public static final int IFS = 13;
  public static final int WH = 7;
  public static final int DED = 60;
  public static final int GT = 47;
  public static final int AO = 45;
  public static final int DO = 40;
}

