
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 07 16:19:11 EET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 73;
  public static final int AS = 64;
  public static final int ANDEQ = 16;
  public static final int FROM = 62;
  public static final int ASTRICKEQ = 13;
  public static final int GROP = 28;
  public static final int INTDIVEQ = 22;
  public static final int ASTRICK = 48;
  public static final int AMBER = 44;
  public static final int LOGNOT = 47;
  public static final int NOTEQ = 18;
  public static final int NEWLINE = 60;
  public static final int PLUSEQ = 11;
  public static final int CSQAURE = 9;
  public static final int OSQUARE = 8;
  public static final int LESSOP = 29;
  public static final int INDENT = 76;
  public static final int COMMA = 7;
  public static final int DEDENT = 77;
  public static final int ELIF = 27;
  public static final int POW = 54;
  public static final int LS = 53;
  public static final int DOUBLE = 74;
  public static final int RS = 52;
  public static final int FALSE = 66;
  public static final int NOT = 33;
  public static final int DEF = 2;
  public static final int ERROR = 78;
  public static final int EQ = 30;
  public static final int OPARAN = 4;
  public static final int MOD = 50;
  public static final int EXCEPT = 68;
  public static final int NUMBER = 41;
  public static final int SLASH = 49;
  public static final int TRUE = 65;
  public static final int NOTIN = 38;
  public static final int PLUS = 45;
  public static final int WHILE = 58;
  public static final int EQUAL = 6;
  public static final int OCURLY = 55;
  public static final int FOR = 57;
  public static final int RETURN = 59;
  public static final int ELSE = 26;
  public static final int TRY = 67;
  public static final int DOUBLEQOUTE = 72;
  public static final int BREAK = 63;
  public static final int DOT = 75;
  public static final int CPARAN = 5;
  public static final int POWEQ = 21;
  public static final int EOF = 0;
  public static final int SEMICOLON = 10;
  public static final int GREQ = 31;
  public static final int IMPORT = 61;
  public static final int ISNOT = 40;
  public static final int IS = 39;
  public static final int MINUS = 46;
  public static final int SINGLEQUOTE = 71;
  public static final int CCURLY = 56;
  public static final int IN = 37;
  public static final int OR = 34;
  public static final int error = 1;
  public static final int LESSEQ = 32;
  public static final int LSEQ = 20;
  public static final int DIVEQ = 14;
  public static final int CONTINUE = 24;
  public static final int IF = 25;
  public static final int ID = 23;
  public static final int MODEQ = 15;
  public static final int BLOCK = 70;
  public static final int COLON = 3;
  public static final int OREQ = 17;
  public static final int NOTEQUAL = 36;
  public static final int STRING = 42;
  public static final int RSEQ = 19;
  public static final int DOUBLESLASH = 51;
  public static final int AND = 35;
  public static final int XOR = 43;
  public static final int MINUSEQ = 12;
  public static final int HASH = 69;
}

